#!/bin/bash
MODULE="receiver"
function log() {
        DATE=`date '+%Y-%m-%d %H:%M:%S'`
        printf "    ${DATE}"
        printf '|%s' "${MODULE}" "$@"
        printf "\n"
}
function assert() {
        CODE=$?
        if [ "$CODE" != "0" ] ; then
                log "FATAL" "FAILURE" "$*" "code=$CODE"
                exit $CODE
        fi
}

APP="$1"
CONTAINER="app/$APP"
log "INFO" "git receiving" "APP=$APP" "CONTAINER=$CONTAINER"

log "Building application container $APP"
log "=========================================================================="
cat | $HOME/bin/build-app-container $CONTAINER
log "=========================================================================="
log "INFO" "SUCCESS"
log "=========================================================================="
log "Starting application $APP"
$HOME/bin/run-app-container $APP $CONTAINER
log "INFO" "Application deployed"
URL=$(< "$HOME/$APP/HOSTNAME")
log "INFO" "       http://$URL"
